financeapp/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^loguot/$', auth_views.logout, {'template_name': 'login.html'}, name='logout'),
    url(r'^index', views.index, name='index'),
    url(r'^dashboard', views.dashboard, name='dashboard'),
    url(r'^create_budget', views.create_budget, name='create_budget'),
    url(r'^mini_budgets', views.mini_budgets, name='mini_budgets'),
    url(r'^detail', views.detail, name='detail')
]

personalfinance/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('financeapp.urls')),
]

financeapp/models.py
from django.db import models
from django.contrib.auth.models import User

class Budget(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length = 50)
    amount = models.FloatField()

    def __str__(self):
        return self.name + ' - ' + self.amount

class MiniBudget(models.Model):
    budget = models.ForeignKey(Budget, on_delete=models.CASCADE)
    name = models.CharField(max_length = 50)
    amount = models.FloatField()

    def __str__(self):
        return self.name + ' - ' + self.amount

financeapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Budget, MiniBudget

class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Enter a valid email address')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

class BudgetForm(forms.ModelForm):

    class Meta:
        model = Budget
        fields = ['name', 'amount']

class MiniBudgetForm(forms.ModelForm):

    class Meta:
        model = MiniBudget
        fields = ['name', 'amount']

financeapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from .forms import SignUpForm, BudgetForm, MiniBudgetForm
from .models import Budget, MiniBudget
from django.db.models import Q
from django.shortcuts import get_object_or_404

def index(request):
    return render(request, 'index.html')

def dashboard(request):
    if not request.user.is_authenticated:
        return render(request, 'login.html')
    budgets = Budget.objects.filter(user=request.user)
    # mini_budgets = MiniBudget.objects.all()
    # query = request.GET.get('q')
    # if query:
    #     budgets = budgets.filter(
    #         Q(name__icontains=query)
    #     ).distinct()
    #     mini_budget_results = mini_budgets.filter(
    #         Q(name__icontains=query)
    #     ).distinct()
    #     return render(request, 'dashboard.html', {'busgets': budgets, 'mini_budgets': mini_budget_results})
    # else:
    return render(request, 'dashboard.html', {'budgets': budgets})

def register(request):
    if not request.user.is_authenticated:
        return render(request, 'login.html')
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('dashboard')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})

def create_budget(request):
    if not request.user.is_authenticated:
        return render(request, 'login.html')
    else:
        form = BudgetForm(request.POST or None)
        if form.is_valid():
            budget = form.save(commit=False)
            budget.user_id = request.user.id
            budget.name = form.cleaned_data['name']
            budget.amount = form.cleaned_data['amount']
            budget.save()
            return render(request, 'detail.html', {'budget': budget})
    return render(request, 'create_budget.html', {'form': form})

def mini_budgets(request):
    return render(request, 'mini_budgets.html')

def detail(request):
    if not request.user.is_authenticated:
        return render(request, 'login.html')
    else:
        user =  request.user
        budget = get_object_or_404(Budget, pk=budget_id)
        return render(request, 'detail.html', {'budget': budget, 'user': user})

financeapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Finance App{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <script src="{% static 'js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'dashboard' %}">Finance App</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block albums_active %}{% endblock %}"><a href="{% url 'dashboard' %}"><span class="glyphicon glyphicon-briefcase" aria-hidden="true"></span>&nbsp; Budgets</a></li>
                <li class="{% block songs_active %}{% endblock %}"><a href="{% url 'mini_budgets' %}"><span class="glyphicon glyphicon-euro" aria-hidden="true"></span>&nbsp; Mini-Budgets</a></li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'index' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'create_budget' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Budget
                    </a>
                </li>
                <li>
                    <a href="{% url 'logout' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

financeapp/templates/base2.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Finance App - {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,400i,700,700i,600,600i">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.min.css">
</head>

<body>
    <nav class="navbar navbar-light navbar-expand-lg fixed-top bg-white clean-navbar">
        <div class="container">
            <a class="navbar-brand logo" href="#">Finance App</a>
            <button class="navbar-toggler" data-toggle="collapse" data-target="#navcol-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navcol-1">
                <ul class="nav navbar-nav ml-auto">
                    <li class="nav-item" role="presentation">
                        <a class="nav-link" href="{% url 'login' %}">login</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    {% block pagecontent %} {% endblock %}
    <footer class="page-footer dark">
        <div class="container">
            <div class="row">
                <div class="col-sm-3">
                    <h5>Get started</h5>
                    <ul>
                        <li>
                            <a href="#">Home</a>
                        </li>
                        <li>
                            <a href="#">Sign up</a>
                        </li>
                        <li>
                            <a href="#">Downloads</a>
                        </li>
                    </ul>
                </div>
                <div class="col-sm-3">
                    <h5>About us</h5>
                    <ul>
                        <li>
                            <a href="#">Company Information</a>
                        </li>
                        <li>
                            <a href="#">Contact us</a>
                        </li>
                        <li>
                            <a href="#">Reviews</a>
                        </li>
                    </ul>
                </div>
                <div class="col-sm-3">
                    <h5>Support</h5>
                    <ul>
                        <li>
                            <a href="#">FAQ</a>
                        </li>
                        <li>
                            <a href="#">Help desk</a>
                        </li>
                        <li>
                            <a href="#">Forums</a>
                        </li>
                    </ul>
                </div>
                <div class="col-sm-3">
                    <h5>Legal</h5>
                    <ul>
                        <li>
                            <a href="#">Terms of Service</a>
                        </li>
                        <li>
                            <a href="#">Terms of Use</a>
                        </li>
                        <li>
                            <a href="#">Privacy Policy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="footer-copyright">
            <p>© 2018 njanelabs.com</p>
        </div>
    </footer>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.0/js/bootstrap.bundle.min.js"></script>
    <script src="{% static '/js/script.min.js' %}"></script>
</body>

</html>

financeapp/templates/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Finance App{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'static/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'static/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'dashboard' %}">Finance App</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'login' %}">Log In</a></li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

financeapp/templates/create_budget.html
{% extends 'base.html' %}
{% block title %}Add a New Budget{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Budget</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="col-sm-12 col-md-5">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>What is Finance App?</h3>
                    <p>Finance App is an app that allows you to create budgets for a specified period of time, and mini budgets within a budget..</p>
                    <h3>Features</h3>
                    <ul>
                        <li>Create a budget</li>
                        <li>Create a mini-budget within a budget</li>
                        <li>Record your financial transactions.</li>
                        <li>See your financial reports.</li>
                    </ul>
                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}

financeapp/templates/create_song.html
{% extends 'music/base.html' %}
{% block title %}Add a New Mini Budget{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                        <a href="{% url 'music:detail' album.id %}">
                            {% if album.album_logo %}
                                <img src="{{ album.album_logo.url }}" class="img-responsive">
                            {% else %}
                                <h3>No image to display</h3>
                            {% endif %}
                        </a>
                    <h1>{{ album.album_title }} <small>{{ album.genre }}</small></h1>
                    <h2>{{ album.artist }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation"><a href="{% url 'music:detail' album.id %}">View All</a></li>
                <li role="presentation" class="active"><a href="{% url 'music:create_song' album.id %}">Add New Song</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Song</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="album" value="{{ album }}">
                        {% include 'music/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

financeapp/templates/dashboard.html
{% extends 'base.html' %}
{% block albums_active %}active{% endblock %}
{% load static %}
{% block body %}
<div class="albums-container container-fluid">

    <!-- Albums -->
    <div class="row">
        <div class="col-sm-12">
            <h3>{{ user.username }}'s Budgets</h3>
        </div>
        {% if budgets %}
            {% for budget in budgets %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'detail' %}">
                            <img src="{% static 'images/dollars.jpg' %}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h2>{{ budget.name }}</h2>
                            <h4>{{ budget.amount }}</h4>

                            <!-- View Details -->
                            <a href="{% url 'detail' %}" class="btn btn-primary btn-sm" role="button">&nbspEdit&nbsp</a>

                            <!-- Delete Budget -->
                            <a href="{% url 'detail' %}" class="btn btn-primary btn-sm" role="button">Delete</a>

                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'create_budget' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add a Budget
                    </button>
                </a>
            </div>
        {% endif %}
    </div>

    <!-- If user searches and there are songs -->
    {% if songs %}
        <div class="row">
            <div class="col-sm-12">
                <h3>Songs</h3>
            </div>
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Song Title</th>
                                    <th>Artist</th>
                                    <th>Audio File</th>
                                    <th>Album</th>
                                    <th>Favorite</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for song in songs %}
                                    <tr>
                                        <td>{{ song.song_title }}</td>
                                        <td>{{ song.album.artist }}</td>
                                        <td>
                                            <a target="_blank" href="{{ song.audio_file.url }}">
                                                <button type="button" class="btn btn-success btn-xs">
                                                    <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                                </button>
                                            </a>
                                        </td>
                                        <td>
                                            <a href="{% url 'detail' song.album.id %}">
                                                <img src="{{ song.album.album_logo.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                            </a>
                                            <a href="{% url 'detail' song.album.id %}">{{ song.album.album_title }}</a>
                                        </td>
                                        <td>
                                            <a href="{% url 'favorite' song.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

</div>
{% endblock %}

financeapp/templates/detail.html
{% extends 'base.html' %}
{% block title %}{{ album }}{% endblock %}
{% block albums_active %}active{% endblock %}
{% load static %}
{% block body %}
<div class="container-fluid songs-container">

    <div class="row">

        <!-- Left Budget Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'detail' budget.id %}">
                        <img src="{% static 'images/dollars.jpg' %}" class="img-responsive">
                    </a>
                    <h1>{{ budget.name }}</h1>
                    <h2>{{ budget.amount }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Mini-Budget Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'detail' budget.id %}">View All</a></li>
                <li role="presentation"><a href="{% url 'create_minibudget' budget.id %}">Add New Song</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All Mini Budgets</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>Amount</th>
                            <th>Progress</th>
                            <th>Record</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for minibudget in budget.minibudget_set.all %}
                            <tr>
                                <td>{{ minibudget.name }}</td>
                                <td>{{ minibudget.amount }}</td>
                                <td>Progress</td>
                                <td>Record</td>
                                <!-- <td>
                                    <form action="{% url 'record' album.id song.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="song_id" value="{{ budget.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Record
                                        </button>
                                    </form>
                                </td> -->
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

financeapp/templates/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

financeapp/templates/index.html
{% extends 'base2.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Home{% endblock %}</title>
</head>
<body>
    {% block pagecontent %}
    <main class="page landing-page">
        <section class="clean-block clean-hero" style="background-image:url(&quot;assets/img/tech/image4.jpg&quot;);color:rgba(9, 162, 255, 0.85);">
            <div class="text">
                <h2>Keep Your Finances in Check</h2>
                <p>Personal finance is hard to do, here comes an easy way to help you achieve financial accountancy.</p>
                <a class="btn btn-outline-light btn-lg" href="{% url 'register' %}" role="button">Get Started</a>
            </div>
        </section>
    </main>
    {% endblock %}
</body>
</html>

financeapp/templates/login.html
{% extends 'base_visitor.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'login'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

financeapp/templates/mini_budgets.html
{% extends 'base.html' %}
{% block title %}Mini Budgets{% endblock %}
{% block songs_active %}active{% endblock %}

{% block body %}
<div class="container-fluid songs-container">

    <div class="row">

        <div class="col-sm-12">

            <div class="panel panel-default">
                <div class="panel-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Mini Budget Name</th>
                                <th>Mini Budget Amount</th>
                                <th>Budget</th>
                                <th>Open</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for song in song_list %}
                                <tr>
                                    <td>{{ song.song_title }}</td>
                                    <td>{{ song.album.artist }}</td>
                                    <td>
                                        <a href="{% url 'detail' song.album.id %}">
                                            <img src="{{ song.album.album_logo.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                        </a>
                                        <a href="{% url 'detail' song.album.id %}">{{ song.album.album_title }}</a>
                                    </td>  
                                    <td>
                                        <a target="_blank" href="{{ song.audio_file.url }}">
                                            <button type="button" class="btn btn-success btn-xs">
                                                <span class="glyphicon glyphicon-open"></span>&nbsp; Open
                                            </button>
                                        </a>
                                    </td>                                                            
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

        </div>

    </div>

</div>
{% endblock %}

financeapp/templates/signup.html
{% extends 'base_visitor.html' %}
{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="{% url 'login' %}">Click here</a> to log in.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}